### ISSUE TITLE
一点小疑问?

### ISSUE THREAD

**Issue by lydlovezjr** [ssseasonnn/Bracer#3]
这个只能在Activit和Fragment传值吗,大佬.

不能在其他地方调用吗
比如我在Adapter,打开一个Activity的话.

**Comment by ssseasonnn** [comment]
可以呀，在哪儿调用都可以

**Comment by lydlovezjr** [comment]
如图,不是这么用的吗,大佬,爆红了.
<img width="730" alt="微信截图_20220816092515" src="https://user-images.githubusercontent.com/19246347/184779165-b2e174f8-fee6-492f-8c94-8a6906c26dd2.png">

**Comment by ssseasonnn** [comment]
把activity或者fragment传给Adapter，然后用activity.params() 或者fragment.params()获取

**Comment by lydlovezjr** [comment]
不传不行吗,这样的话还需要多传递一个参数

似乎是不太行

**Comment by ssseasonnn** [comment]
那肯定不行呀。。总不能凭空来一个参数吧

**Comment by lydlovezjr** [comment]
好的.感谢大佬解惑.
